services:
    acme_mapping_listener:
        class: Acme\ReusableBundle\EventListener\MappingSubscriber
        arguments:
          - %acme_reusable.cart.class%
          - %acme_reusable.cart_line.class%
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }